services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ThieleUndKlose\Autotranslate\EventListener\PageTsConfigListener:
    tags:
      - name: event.listener
        method: "onModifyLoadedPageTsConfig"
        event: TYPO3\CMS\Core\Configuration\Event\ModifyLoadedPageTsConfigEvent

  ThieleUndKlose\Autotranslate\Command\Autotranslate:
    tags:
      - name: console.command
        command: "autotranslate:translate"
        description: "Command for automatic translation."
